# ---
# - name: Update apt repo and cache on all Debian/Ubuntu boxes
#   apt:
#     update_cache: yes
#     cache_valid_time: 3600

# - name: Upgrade all packages on servers
#   apt:
#     name: "*"
#     state: latest

# - name: Sleep 5 seconds
#   wait_for:
#     timeout: 5
#   delegate_to: localhost

# - name: Check if a reboot is needed on all servers
#   register: reboot_required_file
#   stat:
#     path: /var/run/reboot-required
#     get_checksum: no

# - name: Reboot
#   reboot:
  # when: reboot_required_file.stat.exists

---
- name: Update apt repo and cache on all Debian/Ubuntu boxes
  apt:
    name: "*"
    state: latest
    update_cache: yes
    cache_valid_time: 3600

# - name: Upgrade all packages on servers
#   apt:
#     name: "*"
#     state: latest

- name: Sleep 5 seconds
  wait_for:
    timeout: 5
  delegate_to: localhost

- name: Check if a reboot is needed on all servers
  register: reboot_required_file
  stat:
    path: /var/run/reboot-required
    get_checksum: no

- name: Reboot
  reboot:
  when: reboot_required_file.stat.exists