Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.provider :libvirt do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 4096
      libvirt.machine_virtual_size = 40
      libvirt.storage_pool_name = 'boot'
    end
  end