Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
      libvirt.driver = 'kvm'
      libvirt.host = 'localhost'
      libvirt.uri = 'qemu:///system'
  end
    
  config.vm.define 'new' do |custombox|
    custombox.vm.box = 'multi_partitions'

    custombox.vm.provider :libvirt do |test|
      test.cpus = 2
      test.memory = 4096
      test.machine_virtual_size = 40
    end
  end
end
