---
- name: Create directory
  file:
    state: directory
    path: /etc/rancher/rke2/
    
- name: Copy template
  template:
    src: config.yml.j2
    dest: /etc/rancher/rke2/config.yaml
  when: inventory_hostname is match("worker.*")
  become: yes

- name: Start service 
  service:
    name: rke2-agent
    state: started
    enabled: yes

