---
- name: Install required packages
  apt:
    name:
    - vim
    - wget
    - curl
    - net-tools
    state: latest
    update_cache: yes

- name: Make directory
  file:
    path: /home/vagrant/.ssh
    mode: '0700'
    state: directory

- name: Get vagrant.pub
  get_url:
    url: https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub
    dest: /home/vagrant/.ssh/authorized_keys
    mode: '0600'
    validate_certs: no

- name: Restart ssh
  service:
    name: sshd 
    state: restarted
