---

- name: Install rke2 on kubemaster
  shell: |
    curl -sfL https://get.rke2.io | sh -
    systemctl enable rke2-server.service
  when: "inventory_hostname == 'kubemaster'"

- name: Enable the rke2-server service
  service:
    name: rke2-server
    state: started
    enabled: yes
  when: "inventory_hostname == 'kubemaster'"
  

# - name: Install rke2 on the workers
#   shell: |
#     curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sh -
#     systemctl enable rke2-agent.service
#   when: inventory_hostname is match("worker.*")

# - name: Reboot everything
#   reboot:
#   ignore_errors: yes